"""Add rows column to Process model

Revision ID: 0c7b6cf1eb40
Revises: c2b4b4324a58
Create Date: 2023-03-05 21:49:30.498877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7b6cf1eb40'
down_revision = 'c2b4b4324a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.drop_column('pdf_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_data', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
