"""Add rows column to Process model

Revision ID: c2b4b4324a58
Revises: ac6794999173
Create Date: 2023-03-05 18:20:16.064341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b4b4324a58'
down_revision = 'ac6794999173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.drop_column('rows')

    # ### end Alembic commands ###
